global using GameZone.Data;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using GameZone.viewModels;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using GameZone.Models;
global using GameZone.Settings;
global using GameZone.Services;
